create table task (
    id int8 generated by default as identity,
    title varchar(255),
    text varchar(255),
    task_comment_id int8,
    creat_date timestamp,
    update_date timestamp,
    primary key (id)
);

create table task_comment (
    id int8 generated by default as identity,
    user_id int8 not null,
    title varchar(255),
    text varchar(2048),
    creat_date timestamp,
    update_date timestamp,
    primary key (id)
);

create table usr (
    id int8 generated by default as identity not null,
    email varchar(255),
    password varchar(255),
    creat_date timestamp,
    update_date timestamp,
    primary key (id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

alter table if exists task
    add constraint task_task_comment_fk
        foreign key (task_comment_id) references task_comment;

alter table if exists user_role
    add constraint user_role_usr_fk
        foreign key (user_id) references usr;

alter table if exists task_comment
    add constraint task_comment_usr_fk
        foreign key (user_id) references usr;